services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saber-letramento-saude-prod
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge