services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: saber-letramento-saude-dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tailwind.css:/app/tailwind.css
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge